<x-app-layout>
    <x-slot name="header">
        <div class="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
            <div>
                <p class="text-xs font-semibold uppercase tracking-wider text-primary-700">Smart Warehousing</p>
                <h2 class="text-2xl font-bold text-neutral-900">Warehouse Task Registry</h2>
                <p class="text-sm text-neutral-600">Assigned, scan-validated physical work. Creating a task does not change stock.</p>
            </div>
            <x-ui.button variant="secondary" :href="route('inventory.warehousing.dashboard')" icon="arrow-left">Back to Smart Warehousing</x-ui.button>
        </div>
    </x-slot>

    <div class="py-6">
        <div class="mx-auto max-w-7xl space-y-6 sm:px-6 lg:px-8">
            @if ($errors->any())
                <x-ui.alert variant="danger" title="Warehouse task could not be saved">
                    <ul class="list-disc pl-5">@foreach ($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul>
                </x-ui.alert>
            @endif

            <div class="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
                <x-ui.stat label="Open tasks" :value="$metrics['open']" icon="clipboard-document-list" tone="primary" />
                <x-ui.stat label="Overdue" :value="$metrics['overdue']" icon="exclamation-triangle" tone="warning" />
                <x-ui.stat label="Open exceptions" :value="$metrics['exceptions']" icon="exclamation-triangle" tone="danger" />
                <x-ui.stat label="Completed today" :value="$metrics['completed_today']" icon="check-circle" tone="success" />
            </div>

            @can(\App\Enums\Permission::ManageWarehouseTasks->value)
                <x-ui.card title="Create operational task" subtitle="Use for a real physical move, replenishment, or put-away not already generated by a source document.">
                    <form method="POST" action="{{ route('inventory.warehouse-tasks.store') }}" class="grid gap-4 md:grid-cols-2 xl:grid-cols-4">
                        @csrf
                        <div>
                            <label for="task_type" class="text-sm font-medium text-neutral-700">Task type</label>
                            <select id="task_type" name="task_type" required class="mt-1 w-full rounded-lg border-neutral-300">
                                <option value="">Select task type</option>
                                <option value="put_away" @selected(old('task_type') === 'put_away')>Put-away</option>
                                <option value="replenishment" @selected(old('task_type') === 'replenishment')>Pick-face replenishment</option>
                                <option value="move" @selected(old('task_type') === 'move')>Internal movement</option>
                            </select>
                        </div>
                        <div>
                            <label for="priority" class="text-sm font-medium text-neutral-700">Priority</label>
                            <select id="priority" name="priority" required class="mt-1 w-full rounded-lg border-neutral-300">
                                @foreach (['low' => 'Low', 'normal' => 'Normal', 'high' => 'High', 'urgent' => 'Urgent'] as $value => $label)
                                    <option value="{{ $value }}" @selected(old('priority', 'normal') === $value)>{{ $label }}</option>
                                @endforeach
                            </select>
                        </div>
                        <div class="xl:col-span-2">
                            <label for="item_id" class="text-sm font-medium text-neutral-700">Inventory item</label>
                            <select id="item_id" name="item_id" required class="mt-1 w-full rounded-lg border-neutral-300">
                                <option value="">Select item</option>
                                @foreach ($items as $item)<option value="{{ $item->id }}" @selected((string) old('item_id') === (string) $item->id)>{{ $item->name }} ({{ $item->sku }})</option>@endforeach
                            </select>
                        </div>
                        <div>
                            <label for="source_location_id" class="text-sm font-medium text-neutral-700">Source location</label>
                            <select id="source_location_id" name="source_location_id" required class="mt-1 w-full rounded-lg border-neutral-300">
                                <option value="">Select source</option>
                                @foreach ($locations as $location)<option value="{{ $location->id }}" @selected((string) old('source_location_id') === (string) $location->id)>{{ $location->code }} - {{ $location->name }}</option>@endforeach
                            </select>
                        </div>
                        <div>
                            <label for="destination_location_id" class="text-sm font-medium text-neutral-700">Destination location</label>
                            <select id="destination_location_id" name="destination_location_id" required class="mt-1 w-full rounded-lg border-neutral-300">
                                <option value="">Select destination</option>
                                @foreach ($locations as $location)<option value="{{ $location->id }}" @selected((string) old('destination_location_id') === (string) $location->id)>{{ $location->code }} - {{ $location->name }}</option>@endforeach
                            </select>
                        </div>
                        <div>
                            <label for="requested_quantity" class="text-sm font-medium text-neutral-700">Quantity</label>
                            <input id="requested_quantity" name="requested_quantity" type="number" min="1" step="1" required value="{{ old('requested_quantity') }}" class="mt-1 w-full rounded-lg border-neutral-300" inputmode="numeric">
                        </div>
                        <div>
                            <label for="assigned_to_id" class="text-sm font-medium text-neutral-700">Assignee</label>
                            <select id="assigned_to_id" name="assigned_to_id" class="mt-1 w-full rounded-lg border-neutral-300">
                                <option value="">Leave unassigned</option>
                                @foreach ($operators as $operator)<option value="{{ $operator->id }}">{{ $operator->name }} - {{ $operator->role->label() }}</option>@endforeach
                            </select>
                        </div>
                        <div>
                            <label for="due_at" class="text-sm font-medium text-neutral-700">Due at</label>
                            <input id="due_at" name="due_at" type="datetime-local" value="{{ old('due_at') }}" class="mt-1 w-full rounded-lg border-neutral-300">
                        </div>
                        <div class="md:col-span-2 xl:col-span-3">
                            <label for="notes" class="text-sm font-medium text-neutral-700">Operational notes</label>
                            <textarea id="notes" name="notes" rows="2" maxlength="1000" class="mt-1 w-full rounded-lg border-neutral-300">{{ old('notes') }}</textarea>
                        </div>
                        <div class="flex items-end"><x-ui.button type="submit">Create task</x-ui.button></div>
                    </form>
                </x-ui.card>
            @endcan

            <x-ui.card title="Task queue" subtitle="Filter by workflow type or current state.">
                <form method="GET" class="mb-5 grid gap-3 sm:grid-cols-3">
                    <select name="type" class="rounded-lg border-neutral-300">
                        <option value="">All task types</option>
                        @foreach (\App\Enums\WarehouseTaskType::cases() as $type)<option value="{{ $type->value }}" @selected(request('type') === $type->value)>{{ $type->label() }}</option>@endforeach
                    </select>
                    <select name="status" class="rounded-lg border-neutral-300">
                        <option value="">All statuses</option>
                        @foreach (\App\Enums\WarehouseTaskStatus::cases() as $status)<option value="{{ $status->value }}" @selected(request('status') === $status->value)>{{ $status->label() }}</option>@endforeach
                    </select>
                    <x-ui.button type="submit" variant="secondary">Apply filters</x-ui.button>
                </form>

                <x-ui.table>
                    <x-ui.table.head><tr><x-ui.table.th>Task</x-ui.table.th><x-ui.table.th>Item / quantity</x-ui.table.th><x-ui.table.th>Route</x-ui.table.th><x-ui.table.th>Assignee</x-ui.table.th><x-ui.table.th>Status</x-ui.table.th><x-ui.table.th></x-ui.table.th></tr></x-ui.table.head>
                    <tbody>
                    @forelse ($tasks as $task)
                        <x-ui.table.row>
                            <x-ui.table.td><p class="font-mono text-xs font-semibold text-primary-700">{{ $task->task_number }}</p><p>{{ $task->task_type->label() }}</p></x-ui.table.td>
                            <x-ui.table.td>{{ $task->item?->name ?? 'No item' }}<p class="text-xs text-neutral-500">{{ $task->completed_quantity }}/{{ $task->requested_quantity }} {{ $task->item?->unit }}</p></x-ui.table.td>
                            <x-ui.table.td><span class="font-mono text-xs">{{ $task->sourceLocation?->code ?? '—' }} → {{ $task->destinationLocation?->code ?? '—' }}</span></x-ui.table.td>
                            <x-ui.table.td>{{ $task->assignedTo?->name ?? 'Unassigned' }}</x-ui.table.td>
                            <x-ui.table.td><x-ui.badge :status="$task->status->value">{{ $task->status->label() }}</x-ui.badge></x-ui.table.td>
                            <x-ui.table.td><a class="text-sm font-semibold text-primary-700 hover:underline" href="{{ route('inventory.warehouse-tasks.show', $task) }}">Open</a></x-ui.table.td>
                        </x-ui.table.row>
                    @empty
                        <x-ui.table.empty colspan="6" title="No warehouse tasks" message="Tasks appear when work is generated from an eligible workflow or created by a manager." />
                    @endforelse
                    </tbody>
                </x-ui.table>
                <div class="mt-4">{{ $tasks->links() }}</div>
            </x-ui.card>
        </div>
    </div>
</x-app-layout>
